config/routes.rb
Edm::Application.routes.draw do

  resources :users

  match "edm" => "edm#hello"

  match "edm/send" => "edm#edm_send"

  get "edm_sucess" => "edm#edm_sucess"

  get "edm_sample" => "edm#edm_sample"

  match "video" => "video#video"

  root :to => 'edm#hello'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :email_confirm, :password
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/edm_controller.rb
class EdmController < ApplicationController
	def hello

	end

	def edm_send
		session['tmp_email'] = params['email']
		YourMailer.edm(session['tmp_email']).deliver
		redirect_to edm_sucess_path
	end 

	def edm_sucess
		@receiver = session['tmp_email']
		session['tmp_email'] = nil
	end

	def edm_sample
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def index
		@users= User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			flash[:sucess] = "Welcome! from flash message"
			redirect_to @user
		else
		 	render 'new'
		end
	end


end

app/controllers/video_controller.rb
class VideoController < ApplicationController
	def video
		@time = Time.now
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edm_helper.rb
module EdmHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/edm/edm_sample.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>FORD 24 HOUR FIESTA PROJECT</title>
<style type="text/css">
body {
	background-color: #fff;
}
</style>
<body>
<div align="center">

<table width="576" border="0" cellpadding="0" cellspacing="0">
  
  <tr>
  	<td colspan="3" background="http://wantsomeaction.com/fordedm/misc/top.jpg" width="576" height="78">
    	<table width="576" border="0" cellspacing="0" cellpadding="0">
          <tr>
          	<td colspan="3" height="20"></td>
          </tr>
          <tr>
            <td width="35">&nbsp;</td>
            <td valign="top" align="left" style="font-family:Arial, Helvetica, sans-serif; color:#a7aeba; font-size:12px">
            Hi, 
            <br><br>
            We hope you enjoy the latest news and reviews <br> from the world of Ford.
            </td>
            <td width="35">&nbsp;</td>
          </tr>
        </table>
    </td>
  </tr>
  <tr>
    <td width="16" style="background:url(http://wantsomeaction.com/fordedm/misc/shadow_left.jpg) repeat-y">&nbsp;</td>
    <td width="544" valign="top">
    	<table width="544" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td valign="top" align="left">
            <!-- Hero Banner -->
    		<img src="http://yrphilippines.com/newsletter/fordPH/q4/images/hero_banner.jpg" width="544" height="215" alt="The All-New Ford Focus" />
    		<img src="http://wantsomeaction.com/fordedm/misc/in_this_issue.jpg" width="126" height="30" style="margin:10px 0px" />
            </td>
          </tr>
          <tr>
            <td valign="top" align="left" bgcolor="#007ca2" style="padding-left:0px; padding-top:0px">
            <!-- Menu --><a href="#topic1"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item1.jpg" width="82" height="25" border="0" /></a><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item_div.jpg" width="1" height="25" /><a href="#topic2"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item2.jpg" width="116" height="25" border="0" /></a><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item_div.jpg" width="1" height="25" /><a href="#topic3"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item3.jpg" width="120" height="25" border="0" /></a><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item_div.jpg" width="1" height="25" /><a href="#topic4"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item4.jpg" width="140" height="25" border="0" /></a><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item_div.jpg" width="1" height="25" /><a href="#topic5"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/menu_item5.jpg" width="81" height="25" border="0" /></a><!-- End of Menu -->
            </td>
          </tr>

          <tr>
            <td valign="top" align="left">
            	<table width="544" border="0" cellspacing="0" cellpadding="0">                  
                  <tr>
                    <td width="15">&nbsp;</td>
                    <td width="330" valign="top">

                    <h1>Ford Fiesta</h1>
                    <p>

                    <%= link_to image_tag("bc_video.jpg"), url_for({:controller => 'video', :action => 'video'}), target: "_blank" %>
                    </p>
                   
                    </td>
                    
                    
                    <td width="14">&nbsp;</td>
                    
                    
                    <td valign="top">
                     <table background="http://yrphilippines.com/newsletter/fordPH/q4/images/details-web-2.jpg" width="185" height="95" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td colspan="1" height="15"></td>
                          </tr>
                         
                          <tr>
                            <td>&nbsp;</td>
                              </tr>
                  
                          <tr>
                            <td width="37">&nbsp;</td>
                            <td valign="top" align="left"><a href="https://www.secure.ford.com.ph/customer-update-form" target="_blank"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/update.jpg" width="112" height="33" alt="Find us on Facebook" border="0" /></a></td>
                          </tr>
                        </table>
                        <br/>
                    	
                   	  <table background="http://wantsomeaction.com/fordedm/misc/here_to_help_bckgrnd2.jpg" width="185" height="203" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td colspan="2" height="40">&nbsp;</td>
                          </tr>
                          <tr>
                            <td width="20">&nbsp;</td>
                            <td valign="top" align="left" height="20"><a href="http://www.ford.com.ph/service/service-page" target="_blank"><img src="http://wantsomeaction.com/fordedm/misc/btn_ford_service.jpg" width="114" height="15" alt="Ford Services" border="0" /></a>
                            </td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td valign="top" align="left" height="15"><a href="http://www.ford.com.ph/" target="_blank"><img src="http://wantsomeaction.com/fordedm/misc/btn_ford-ph.jpg" width="114" height="15" alt="Ford Philippines" border="0" /></a></td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td valign="top" height="15" align="left"><a href="https://www.secure.ford.com.ph/brochure" target="_blank"><img src="http://wantsomeaction.com/fordedm/misc/btn_download_brochure.jpg" border="0" width="113" height="15" alt="Download Brochures" /></a></td>
                          </tr>
                          <tr>
                          	<td>&nbsp;</td>
                            <td><p style="font-family:Arial; font-size:11px; color:#6d737d"><strong>Hotline Numbers :</strong><br />
                            +63-2-866-9408<br />
                            1-800-10-736-3673<br />
                            </p>
                            </td>
                          </tr>
                          <tr>
                            <td width="20">&nbsp;</td>
                            <td valign="top" align="left"><a href="http://www.facebook.com/FordPhilippines" target="_blank"><img src="http://wantsomeaction.com/fordedm/misc/btn_facebook.jpg" width="21" height="31" alt="Find us on Facebook" border="0" /></a><span>&nbsp;</span><a href="https://twitter.com/#!/FordPhilippines" target="_blank"><img src="http://wantsomeaction.com/fordedm/misc/btn_twitter.jpg" width="22" height="31" alt="Follow us on Twitter" border="0" /></a></td>
                          </tr>
                        </table>
                        
                        <br>
                        
                        <table background="http://yrphilippines.com/newsletter/fordPH/q4/images/hotdeals_offer_bckgrnd.jpg" width="185" height="122" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                          	<td width="5">&nbsp;</td>
                           <td align="center"><a href="http://www.ford.com.ph/buying/hot-deals" target="_blank"><img src="http://yrphilippines.com/newsletter/fordPH/q4/images/hotdeals_offer_yec.jpg" width="175" height="76" /></a></td>
                          </tr>
                        </table>
                        
                        
                        <br>
                        
                        
                      <table background="http://wantsomeaction.com/fordedm/misc/did_you_know_bckgrnd.jpg" height="153" width="185" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                          	<td height="37" colspan="3">&nbsp;</td>
                          </tr>
                          <tr>
                            <td width="15">&nbsp;</td>
                            <td valign="top" align="left">
                            <font color="#535553" style="font-size:11px; font-family:Arial">
                           By 2016 Ford plans to decrease the energy it uses to make their vehicles by 25%. 
                            </font>
                            </td>
                            <td width="10">&nbsp;</td>
                          </tr>
                        </table>
               	    </td>
                  </tr>                                    
                </table>
            </td>
          </tr>
        </table>
        
    </td>
    <td width="16" style="background:url(http://wantsomeaction.com/fordedm/misc/shadow_right.jpg) repeat-y">&nbsp;</td>
  </tr>
  <tr>
  	<td colspan="3"><img src="http://wantsomeaction.com/fordedm/misc/bottom.jpg" width="576" height="35" /></td>
  </tr>
  <tr>
  	<td colspan="3" align="center">
    	<a style="font-size:11px; color:#808285; font-family:arial; text-decoration:none" href="https://www.secure.ford.com.ph/contact-us">Unsubscribe</a><font style="margin:0px 10px">|</font><a href="http://www.ford.com.ph/privacy-and-disclaimer" target="_blank" style="font-size:11px; color:#808285; font-family:arial; text-decoration:none">Privacy Policy</a>        
    </td>
  </tr>
  <tr>
  	<td colspan="3" height="40" align="center"><font style="font-size:11px; color:#808285; font-family:arial; text-decoration:none">&copy; 2013 Ford Group Philippines. All rights reserved.</font></td>
  </tr>
</table>
</div>
</body>
</html>

app/views/edm/edm_send.html.erb
<h1>Thank You</h1>

<h1><%= @receiver %></h1>

<%= params.inspect %>

app/views/edm/edm_sucess.html.erb
<h1>Thank You</h1>

<h1><%= @receiver %></h1>

app/views/edm/hello.html.erb
<h1>Send EDM</h1>

<%= form_tag(edm_send_path, {class: 'pure-form'}) do %>

<p><%= email_field_tag 'email', nil , placeholder: 'Enter email address', size: 35, class: 'pure-input' %></p>

<%= submit_tag 'SEND!', class: 'button-cta pure-button' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brightcove Edm Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure-min.css">

  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

  <style type="text/css">
  .container {
  	text-align: center;
  }

  .top-menu {
  	background: #191818;
  }

  .pure-button{
  	font-size: 125%;
  }

  </style>



<!--[if lt IE 9]>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
<![endif]-->

</head>
<body>
	<div class="top-menu pure-menu pure-menu-open pure-menu-horizontal">
		<ul>
		<li class="pure-menu-selected"><%= link_to "Send EDM", edm_path%></li>
		<li><%= link_to "Brightcove Demo", video_path %></li>
		<li><%= link_to "EDM Sample", edm_sample_path %></li>
		</ul>
	</div>
	</div>

	<div class="container">
	<div class="pure-g">
        <div class="pure-u-5-5">
            <% flash.each do |k,y| %>
              <%= y %>
            <% end %>
            <%= yield %>
        </div>
	</div>
	</div>
</body>
</html>

 <script>
    $("form").validate();
</script>

app/views/shared/_error.html.erb
ERRRORS¡

app/views/users/index.html.erb
<h1>users </h1>

<% @users.each do |f| %>
	<li><%= f.id %> - <%= f.email %></li>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'shared/error'%>

<%= form_for(@user) do |f|%>
	<%= f.label :email %>
	<%= f.text_field :email %>
	</br>
	<%= f.label :email_confirm %>
	<%= f.text_field :email_confirm %>
		</br>
	<%= f.label :password %>
	<%= f.password_field :password %>
		</br>

	<%= f.submit :submit, class: "button-cta pure-button" %>
<% end %>

app/views/users/show.html.erb
<h1>User </h1>

<%= @user.id %>

<%= @user.email %>


<%= debug(params)%>

app/views/video/video.html.erb
<!-- Start of Brightcove Player -->

<h1>Brightcove Sample Video</h1>

<div style="display:none">

</div>

<!--
By use of this code snippet, I agree to the Brightcove Publisher T and C 
found at https://accounts.brightcove.com/en/terms-and-conditions/. 
-->

<script language="JavaScript" type="text/javascript" src="http://admin.brightcove.com/js/BrightcoveExperiences.js"></script>

<object id="myExperience2638716113001" class="BrightcoveExperience">
  <param name="bgcolor" value="#FFFFFF" />
  <param name="width" value="960" />
  <param name="height" value="540" />
  <param name="playerID" value="2568025248001" />
  <param name="playerKey" value="AQ~~,AAACKhr-28E~,JKU8InpPHa1UbPMh5zonZM1cznYylUih" />
  <param name="isVid" value="true" />
  <param name="isUI" value="true" />
  <param name="dynamicStreaming" value="true" />
  
  <param name="@videoPlayer" value="2638716113001" />
</object>

<!-- 
This script tag will cause the Brightcove Players defined above it to be created as soon
as the line is read by the browser. If you wish to have the player instantiated only after
the rest of the HTML is processed and the page load is complete, remove the line.
-->
<script type="text/javascript">brightcove.createExperiences();</script>

<!-- End of Brightcove Player -->